title:            I exist as I am
tagline:          Do not go where the path may lead, go instead where there is no path and leave a trail.<br/> --Ralph Waldo Emerson
description: 

#I exist as I am, that is enough, If no other in the world be aware I sit content, And if each and all be aware I sit content. One world is aware, and by the far the largest to me, and that is myself, And whether I come to my own today or in ten thousand or ten million years, I can cheerfully take it now, or with equal cheerfulness, I can wait. ― Walt Whitman

# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://jared.ottleys.net

# Owner/author information
owner:
  name:           Jared Ottley
  avatar:         Headshot Coach.jpeg
  bio:            "Jared Ottley is an Engineer at <a href='http://www.hyland.com'>Hyland</a> working on the Alfresco Platform.  To wind down he coaches lacrosse Springville High School. He is the proud father of 6."
  email:          jared@ottleys.net
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        jottley
  facebook:       jottley
  github:         jottley
  linkedin:       jottley
  instagram:      jaredrottley
  #lastfm:         user/jottley
  flickr:         jottley
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    https://plus.google.com/u/0/116380333940951424604/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-73397-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - .htaccess
  - node_modules/uglifier/index.js
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/